name: Pareiovision Shop Deployment
on:
  push:
    paths:
    - "./pareiovision-shopify/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Shop to www subdomain
        run: npm install && npm run build && aws s3 sync build/ s3://${{ secrets.WWW_SHOP_AWS_S3_BUCKET }} --delete
      - name: Deploy Shop to subdomain
        run: aws s3 sync build/ s3://${{ secrets.DOMAIN_SHOP_AWS_S3_BUCKET }} --delete
